INSERT INTO `API-palabras`.palabra (`id`, `palabra`) VALUES
                                                            (1, 'word1'),
                                                            (2, 'word2'),
                                                            (3, 'word3'),
                                                            (4, 'word4'),
                                                            (5, 'word5'),
                                                            (6, 'word6'),
                                                            (7, 'word7'),
                                                            (8, 'word8'),
                                                            (9, 'word9'),
                                                            (10, 'word10'),
                                                            (11, 'word11'),
                                                            (12, 'word12'),
                                                            (13, 'word13'),
                                                            (14, 'word14'),
                                                            (15, 'word15');