-- MySQL Script generated by MySQL Workbench
-- Mon Dec  4 09:52:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema API-palabras
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema API-palabras
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `API-palabras` DEFAULT CHARACTER SET utf8 ;
USE `API-palabras` ;

-- -----------------------------------------------------
-- Table `API-palabras`.`Equipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `API-palabras`.`Equipo` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `score` INT NULL,
  `badge` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `API-palabras`.`Jugador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `API-palabras`.`Jugador` (
  `id` INT NOT NULL,
  `user` VARCHAR(45) NOT NULL,
  `score` INT NULL,
  `avatar_img` BLOB NULL,
  `Equipo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Equipo_id`),
  INDEX `fk_Jugador_Equipo1_idx` (`Equipo_id` ASC) VISIBLE,
  CONSTRAINT `fk_Jugador_Equipo1`
    FOREIGN KEY (`Equipo_id`)
    REFERENCES `API-palabras`.`Equipo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `API-palabras`.`Juego`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `API-palabras`.`Juego` (
  `id` INT NOT NULL,
  `difficulty_j` ENUM('facil', 'normal', 'dificil') NOT NULL,
  `max_tries` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `API-palabras`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `API-palabras`.`Partida` (
  `id` INT NOT NULL,
  `word` VARCHAR(45) NOT NULL,
  `n_try` INT NOT NULL,
  `score` INT NULL,
  `date_time` DATE NULL,
  `Jugador_id` INT NOT NULL,
  `Jugador_Equipo_id` INT NOT NULL,
  `Juego_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Juego_id`),
  INDEX `fk_Partida_Jugador1_idx` (`Jugador_id` ASC, `Jugador_Equipo_id` ASC) VISIBLE,
  INDEX `fk_Partida_Juego1_idx` (`Juego_id` ASC) VISIBLE,
  CONSTRAINT `fk_Partida_Jugador1`
    FOREIGN KEY (`Jugador_id` , `Jugador_Equipo_id`)
    REFERENCES `API-palabras`.`Jugador` (`id` , `Equipo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Juego1`
    FOREIGN KEY (`Juego_id`)
    REFERENCES `API-palabras`.`Juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `API-palabras`.`Palabra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `API-palabras`.`Palabra` (
  `id` INT NOT NULL,
  `palabra` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `API-palabras`.`Juego_has_Palabra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `API-palabras`.`Juego_has_Palabra` (
  `Juego_id` INT NOT NULL,
  `Palabra_id` INT NOT NULL,
  `difficulty_p` ENUM('facil', 'normal', 'dificil') NULL,
  PRIMARY KEY (`Juego_id`, `Palabra_id`),
  INDEX `fk_Juego_has_Palabra_Palabra1_idx` (`Palabra_id` ASC) VISIBLE,
  INDEX `fk_Juego_has_Palabra_Juego_idx` (`Juego_id` ASC) VISIBLE,
  CONSTRAINT `fk_Juego_has_Palabra_Juego`
    FOREIGN KEY (`Juego_id`)
    REFERENCES `API-palabras`.`Juego` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Juego_has_Palabra_Palabra1`
    FOREIGN KEY (`Palabra_id`)
    REFERENCES `API-palabras`.`Palabra` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
